# This is an OpenEMPIRE configuration file used for test runs.
# To be used with the execution script run.py

use_temporary_directory: True
temporary_directory: './'    
forecast_horizon_year: 2025
number_of_scenarios: 1      
length_of_regular_season: 2178 # (8760-24*2)/4
discount_rate: 0.085
wacc: 0.085
optimization_solver: "Gurobi"
use_scenario_generation: True
use_fixed_sample: False
load_change_module: False
filter_make : False
filter_use : False
n_cluster : 10
moment_matching : False
n_tree_compare : 20
use_emission_cap: False
compute_operational_duals: True
print_in_iamc_format: False
write_in_lp_format: True
serialize_instance: False
north_sea: False
# regular_seasons: ["year"]
n_peak_seasons: 2
len_peak_season: 24
leap_years_investment: 5
